name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish ./WeatherApi/WeatherApi.csproj -c Release -o ./publish

      - name: Deploy pomocí Web Deploy
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -source:contentPath="$(System.DefaultWorkingDirectory)\publish"
          -dest:contentPath=${{ secrets.SITE_NAME }},
          computerName="https://${{ secrets.DEPLOY_SERVER }}:8172/msdeploy.axd?site=${{ secrets.SITE_NAME }}",
          userName=${{ secrets.DEPLOY_USER }},
          password=${{ secrets.DEPLOY_PASSWORD }},
          authType="Basic"
          -verb:sync
          -allowUntrusted