name: Deploy to IIS

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Volitelný: ID buildu (run-id), ze kterého se má stáhnout artefakt'
        required: false

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Nastavit GitHub CLI
      uses: actions/setup-gh@v1

    - name: Zjistit run ID
      id: resolve-run-id
      run: |
        if [ -z "${{ github.event.inputs.build_run_id }}" ]; then
          echo "Žádný build_run_id nezadán – hledám poslední run z větve 'master'..."
          run_id=$(gh run list --workflow ".NET" --branch master --status success --limit 1 --json databaseId --jq ".[0].databaseId")
        else
          echo "Používám ručně zadaný run ID: ${{ github.event.inputs.build_run_id }}"
          run_id=${{ github.event.inputs.build_run_id }}
        fi
        echo "RUN_ID=$run_id" >> $GITHUB_ENV
        echo "Použitý run ID: $run_id"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stáhnout artefakt z runu
      run: gh run download "$RUN_ID" --name weather-api-publish --dir ./publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Nasazení na IIS přes Web Deploy
      run: >
        "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
        -source:contentPath="$(System.DefaultWorkingDirectory)\publish"
        -dest:contentPath=${{ secrets.SITE_NAME }},
        computerName="https://${{ secrets.DEPLOY_SERVER }}:8172/msdeploy.axd?site=${{ secrets.SITE_NAME }}",
        userName=${{ secrets.DEPLOY_USER }},
        password=${{ secrets.DEPLOY_PASSWORD }},
        authType="Basic"
        -verb:sync
        -allowUntrusted