name: Build & Optional Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Spustit deploy? (ano/ne)'
        required: false
        default: 'ne'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      should_deploy: ${{ github.event.inputs.deploy }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ./WeatherApi/WeatherApi.csproj -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-api-publish
        path: ./publish

  deploy:
    needs: build
    if: ${{ github.event.inputs.deploy == 'ano' }}
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: weather-api-publish
        path: ./publish

    - name: Deploy to IIS via Web Deploy
      run: >
        "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
        -source:contentPath="$(System.DefaultWorkingDirectory)\publish"
        -dest:contentPath=${{ secrets.SITE_NAME }},
        computerName="https://${{ secrets.DEPLOY_SERVER }}:8172/msdeploy.axd?site=${{ secrets.SITE_NAME }}",
        userName=${{ secrets.DEPLOY_USER }},
        password=${{ secrets.DEPLOY_PASSWORD }},
        authType="Basic"
        -verb:sync
        -allowUntrusted